### ISSUE TITLE
你好 我想请问一下我想自定义回复  具体该怎么操作

### ISSUE THREAD

**Issue by NNanfeng** [ngc660sec/NGCBot#1]
也就是每次回复的内容 根据接收到的消息后缀不同回复不同的内容   调用别的函数进行回复结果的返回值

**Comment by ngc660sec** [comment]
您好，针对您这种需求，需要判断您消息的后缀，首页是需要看keyword变量中您的后缀是什么，再去Api_Server_Main文件中写相应函数去，在RoomMsg_dispose文件中调用函数这个需求的关键点在于判断您的消息后缀，如果可以，请提供一个实例，谢谢！

**Comment by NNanfeng** [comment]
你好 感谢您的回答  我已经写好了 能正常运行了，但是我感觉您的机器人没有做异步处理，所以可能会有卡死的时候

**Comment by ngc660sec** [comment]
感谢您的建议，这边会持续更新优化的，多谢！
