### ISSUE TITLE
如何自动转发图片？

### ISSUE THREAD

**Issue by fengfeng163** [ngc660sec/NGCBot#11]
看了例子，只能转发文字消息，好友发的图片怎么自动转发？先下载图片吗？但是不知道怎么下载微信图片。

**Comment by ngc660sec** [comment]
你好，好友图片暂时不支持转发
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月23日 09:14
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [ngc660sec/NGCBot] 如何自动转发图片？ (Issue #11)
        
      
    
  

看了例子，只能转发文字消息，好友发的图片怎么自动转发？先下载图片吗？但是不知道怎么下载微信图片。
