### ISSUE TITLE
功能建议：建议支持导出通讯录，实现微信备份功能

### ISSUE THREAD

**Issue by zhanggaoxuan** [ngc660sec/NGCBot#12]
建议支持导出通讯录，实现微信备份功能，导出为excel的csv或者xlsx

**Comment by ngc660sec** [comment]
没理解意思，是导出通讯录的好友嘛 还是说连好友消息也一起保存下载

**Comment by zhanggaoxuan** [comment]
> 没理解意思，是导出通讯录的好友嘛 还是说连好友消息也一起保存下载

导出通讯录好友。
（消息不用备份。因为消息太多，而且也得找地方恢复）

导出通讯录好友可以用来防止因为封号等导致的失联
