### ISSUE TITLE
错误10061，已注入

### ISSUE THREAD

**Issue by hanshaoUi** [ngc660sec/NGCBot#14]
微信版本：3.2.1.121
已运行注入程序

![image](https://github.com/ngc660sec/NGCBot/assets/54573836/8408a480-728c-4597-8919-55e4c2c4bdb8)

![image](https://github.com/ngc660sec/NGCBot/assets/54573836/09f5ad5f-1e37-4664-b83c-f67c60716e79)

**Comment by ngc660sec** [comment]
使用管理员权限打开注入器注入试试
