### ISSUE TITLE
是接口的问题吗

### ISSUE THREAD

**Issue by tlpzzm** [ngc660sec/NGCBot#18]
![图片](https://github.com/ngc660sec/NGCBot/assets/133225222/addf7cd7-8a3f-4643-91b0-ee9aa02be66b)
在群里at他,都不回复的

**Comment by ngc660sec** [comment]
不要挂代理 并且确保key能够使用

**Comment by zhangyuhaimian** [comment]
我也遇到这个情况，help也不行如何解决

**Comment by ngc660sec** [comment]
> 我也遇到这个情况，help也不行如何解决

help不回复还是怎么样

**Comment by zhangyuhaimian** [comment]
解决了 ，加了个sk key解决了

**Comment by ngc660sec** [comment]
好的

**Comment by zhangyuhaimian** [comment]
![image](https://github.com/ngc660sec/NGCBot/assets/124965563/12c98d02-0913-407b-b7a2-abf1339fca22)
这个问题如何解决

**Comment by zhangyuhaimian** [comment]
![image](https://github.com/ngc660sec/NGCBot/assets/124965563/340e2285-b075-4a5e-8ee7-305d6f321c4a)

**Comment by ngc660sec** [comment]
> ![image](https://user-images.githubusercontent.com/124965563/267306396-340e2285-b075-4a5e-8ee7-305d6f321c4a.png)

你好 请参考以前的iessus
