### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by adminlove520** [ngc660sec/NGCBot#2]
您好 请问运行报错这个是怎么回事呀
![image](https://user-images.githubusercontent.com/32920883/211701574-64fc0aa4-7ad5-442a-ade3-b2c185d7abd3.png)

**Comment by adminlove520** [comment]
添加特权群聊 会报错 然后CVE推送这个可以加一下关键词获取嘛

**Comment by adminlove520** [comment]
有时候会报错：错误信息：wx_id、wx_name  这种错误

**Comment by adminlove520** [comment]
请问CVE监控是如何推送的呀？没看到定时推送的逻辑呀  或者什么关键词触发呢

**Comment by ngc660sec** [comment]
您好，首先是第一个问题，需要先打开注入器进行注入，记得挑选适合的微信版本，在我的iessus下都有相应文件，如果没找到，可能是我没上传。
第二个问题添加特权群聊会报错，这个问题需要根据报错内容来判定，如果可以吗，还请提供一下相关截图，再是CVE关键词获取，在config.yaml文件中是存在关键词获取的相关配置的
![image](https://user-images.githubusercontent.com/52269948/211974305-acffb755-40d9-4367-b444-800dec5422d0.png)

第三个问题，也是请提供一下相关截图，因为有很多可能性会导致这个问题，从我本地目前的运行状况来讲，一般是不会轻易报这个错的

第四个问题，CVE监控的相关代码文件在Monitor_Server目录下，只要检测到了更新就会发送更新内容至特权群聊，并没有关键词触发，实际上只是一个监控作用，定时推送的逻辑在Push_Main_Server文件中
![image](https://user-images.githubusercontent.com/52269948/211974667-82a6e185-2b5c-4d71-a660-aa2e7190fe11.png)
30表示的是30分钟监控一次。

如有其它问题，最好是附带报错截图联系我，谢谢！

**Comment by adminlove520** [comment]
![image](https://user-images.githubusercontent.com/32920883/212650206-b0f8a446-73f0-4204-9bc5-43a7e0c58f47.png)
这个问题是发送添加特权群聊没有反应，后台也没有报错  config.yaml如下：
![image](https://user-images.githubusercontent.com/32920883/212650988-da09fb65-7f06-4e58-8f83-6b1277f44577.png)
这个是wx_id:
![Uploading image.png…]()
和config.yaml吻合
请问是需要在管理员关键词里面新增一个规则嘛

**Comment by ngc660sec** [comment]
你好，目前添加特权群聊已改名为白名单群聊，相关触发配置在config文件当中
![image](https://user-images.githubusercontent.com/52269948/212651687-c690b822-0dcc-4c31-8159-99e64550fa2c.png)

**Comment by adminlove520** [comment]
但是开启推送服务后无法收到cve推送，后台因为没有日志文件 所以也不太好定位错误

**Comment by ngc660sec** [comment]
目前的cve监控是每30分钟监控一次，在这个过程中是不会有任何提示的，只有到时间触发的时候会输出相应的日志信息

**Comment by adminlove520** [comment]
![image](https://user-images.githubusercontent.com/32920883/212653928-d0e808ae-bd77-4633-a2cf-9623dd298133.png)
这个是群聊中@机器人 清空缓存会报错这个

**Comment by adminlove520** [comment]
那您那边本地的群聊是正常推送cve嘛？

**Comment by ngc660sec** [comment]
你好，目前清空缓存的功能只能用于私聊，不能在群聊中@机器人清空

**Comment by ngc660sec** [comment]
这边是正常推送cve信息的

**Comment by adminlove520** [comment]
![image](https://user-images.githubusercontent.com/32920883/212656360-5af3c122-a42a-4c75-886b-4e3991297c68.png)
我改成1秒获取cve 然后报了这个错  gh_token也配置了的

**Comment by adminlove520** [comment]
请问是哪里需要改动嘛

**Comment by adminlove520** [comment]
这个感觉是数据库出问题了 游标报错，但是数据库都是初始化的，关于cve推送也没有其他改动

**Comment by adminlove520** [comment]
请问可以加下wx，交流下嘛

**Comment by ngc660sec** [comment]
好的，这个问题我后续优化，可以添加我的微信工作号NGC660_Sec

**Comment by LiangYao17** [comment]
![image](https://user-images.githubusercontent.com/115398805/223927323-9b0f7fe3-5efe-4378-807d-ca1384e1dcb1.png)
请问这个是什么问题

**Comment by ngc660sec** [comment]
> ![image](https://user-images.githubusercontent.com/115398805/223927323-9b0f7fe3-5efe-4378-807d-ca1384e1dcb1.png) 请问这个是什么问题

你好，应该是AI对话接口故障

**Comment by zero150717** [comment]
> 
麻烦问一下您如何解决这个问题了

**Comment by Crazy-FuQing** [comment]
wx_id、wx_name 这种错误  该如何排查呢
![image](https://github.com/ngc660sec/NGCBot/assets/46838021/14a97085-b3f5-46d8-80eb-37ae4da275ce)

**Comment by ngc660sec** [comment]
> wx_id、wx_name 这种错误 该如何排查呢 ![image](https://user-images.githubusercontent.com/46838021/267253776-14a97085-b3f5-46d8-80eb-37ae4da275ce.png)

检查Python版本是否是3.8 建议用3.8.10版本，查看微信号是否修改过，不能用默认的微信号

**Comment by Crazy-FuQing** [comment]
> > wx_id、wx_name 这种错误 该如何排查呢 ![image](https://user-images.githubusercontent.com/46838021/267253776-14a97085-b3f5-46d8-80eb-37ae4da275ce.png)
> 
> 检查Python版本是否是3.8 建议用3.8.10版本，查看微信号是否修改过，不能用默认的微信号

感谢回复，截图中有写，wxid_npc9bcibvqqf21就是我的wx号，并且写入了配置文件，另外我检查了下版本，3.8.0，可以将您的python文件夹打包发我吗
![1694511402816](https://github.com/ngc660sec/NGCBot/assets/46838021/f0e1dd76-2c57-4c9f-a0ff-8b32bd086b27)

**Comment by ngc660sec** [comment]
> > > wx_id、wx_name 这种错误 该如何排查呢 ![image](https://user-images.githubusercontent.com/46838021/267253776-14a97085-b3f5-46d8-80eb-37ae4da275ce.png)
> > 
> > 
> > 检查Python版本是否是3.8 建议用3.8.10版本，查看微信号是否修改过，不能用默认的微信号
> 
> 感谢回复，截图中有写，wxid_npc9bcibvqqf21就是我的wx号，并且写入了配置文件，另外我检查了下版本，3.8.0，可以将您的python文件夹打包发我吗 ![1694511402816](https://user-images.githubusercontent.com/46838021/267290626-f0e1dd76-2c57-4c9f-a0ff-8b32bd086b27.png)

请用3.8.10试试，另外请截图你的微信名和微信ID给我看看，在此处
![image](https://github.com/ngc660sec/NGCBot/assets/52269948/e87dc081-82de-4218-9ae1-677fd7d92799)

**Comment by Crazy-FuQing** [comment]
> > > > wx_id、wx_name 这种错误 该如何排查呢 ![image](https://user-images.githubusercontent.com/46838021/267253776-14a97085-b3f5-46d8-80eb-37ae4da275ce.png)
> > > 
> > > 
> > > 检查Python版本是否是3.8 建议用3.8.10版本，查看微信号是否修改过，不能用默认的微信号
> > 
> > 
> > 感谢回复，截图中有写，wxid_npc9bcibvqqf21就是我的wx号，并且写入了配置文件，另外我检查了下版本，3.8.0，可以将您的python文件夹打包发我吗 ![1694511402816](https://user-images.githubusercontent.com/46838021/267290626-f0e1dd76-2c57-4c9f-a0ff-8b32bd086b27.png)
> 
> 请用3.8.10试试，另外请截图你的微信名和微信ID给我看看，在此处 ![image](https://user-images.githubusercontent.com/52269948/267291594-e87dc081-82de-4218-9ae1-677fd7d92799.png)

关于这个问题 我貌似找到了原因，我将py文件默认程序修改为python打开后突然就行了，不清楚具体原因
![1694513254307](https://github.com/ngc660sec/NGCBot/assets/46838021/750b63a5-ca09-46b7-8580-6c67f56d3fff)
![1694513269718](https://github.com/ngc660sec/NGCBot/assets/46838021/dc04715f-2e92-4857-a05e-426fbfb25ec6)

**Comment by ngc660sec** [comment]
好的
