### ISSUE TITLE
好项目，请问有打赏的入口吗

### ISSUE THREAD

**Issue by chappiewuzefan** [ngc660sec/NGCBot#20]
有一个小疑问，这个项目会不会封号哇

**Comment by ngc660sec** [comment]
已稳定运行一年
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月6日 09:09
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [ngc660sec/NGCBot] 好项目，请问有打赏的入口吗 (Issue #20)
        
      
    
  

有一个小疑问，这个项目会不会封号哇
