### ISSUE TITLE
二次启动程序出现连接问题，需重启微信

### ISSUE THREAD

**Issue by zlong2** [ngc660sec/NGCBot#23]
您好：
![image](https://github.com/ngc660sec/NGCBot/assets/101798054/26fc4bce-a0be-4288-99ac-0ca1c0236bd6)
第一次启动程序没问题
![image](https://github.com/ngc660sec/NGCBot/assets/101798054/ca219629-48e2-4212-9462-8152a573bc9e)
第二次出现连接问题，通过任务管理器关掉微信重新打开后才正常
![image](https://github.com/ngc660sec/NGCBot/assets/101798054/2ae4f8f2-aa6e-409e-8e52-a6f73266e0cb)
上面这个问题是没有打最新版dll导致的吗，但我在Release里面也没找到新版的注入器
![image](https://github.com/ngc660sec/NGCBot/assets/101798054/c3b7facc-7318-4136-ab23-d74290e222a3)
解压之后也没有看见。
![image](https://github.com/ngc660sec/NGCBot/assets/101798054/048c00ed-4373-4ca4-9229-5a7963bacd95)
![image](https://github.com/ngc660sec/NGCBot/assets/101798054/be708692-3c9e-4fbf-a4fa-44cfcf290884)

**Comment by ngc660sec** [comment]
你好师傅，因为采用了最新框架和注入器所以会导致这个问题，我正在努力修复中，未修复成功之前，还是需要采用老办法 重启微信

**Comment by longtzx** [comment]
我是远程调用失败，然后也是不行，重启了还是不行

**Comment by ngc660sec** [comment]
必须要用任务管理器去关闭 不然有进程残留
