### ISSUE TITLE
反馈一些bug

### ISSUE THREAD

**Issue by komomon** [ngc660sec/NGCBot#28]
1.吃cpu巨高，2.6GHz win服务器，要吃掉50%CPU
![image](https://github.com/ngc660sec/NGCBot/assets/52700174/c1b9f149-3241-4d51-8b74-2f8b79d5b6ff)

2.当Room_Key_Word这个标签下的群组不存在的时候，关键词触发后会循环执行query_room_name函数，“一直输出不存在此群, 正在尝试添加到库... ...”，像是死循环，使得cpu跑到99%，正常应该跳出去，或者给与administrator发一个消息。这个就不截图，可以自己加一个不存在的标签触发加群，试试看。

**Comment by ngc660sec** [comment]
逻辑是这样 不能跳出去 跳出去就获取不到群聊名字 可以试着加延时

**Comment by komomon** [comment]
> 逻辑是这样 不能跳出去 跳出去就获取不到群聊名字 可以试着加延时

1、为什么吃cpu这么多呢，wcf库还是本身的某些代码吃cpu多呢，
2、能不能改成，配置文件或者代码动态加载，修改自动重载类似flask的修改代码重新加载呢。

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    热加载后面我可以看一看
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月22日 14:35
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 反馈一些bug (Issue #28)
        
      
    
  
  

逻辑是这样 不能跳出去 跳出去就获取不到群聊名字 可以试着加延时

1、为什么吃cpu这么多呢，wcf库还是本身的某些代码吃cpu多呢，
2、能不能改成，配置文件或者代码动态加载，修改自动重载类似flask的修改代码重新加载呢。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
