### ISSUE TITLE
相关问题请点我

### ISSUE THREAD

**Issue by ngc660sec** [ngc660sec/NGCBot#3]
1. 如可以，请附带详细的报错截图，如果您知道报错位置，也望告知
2. 详细描述您所遇到的问题，这边会尽快解答
3. 介于本人时间问题，一般的问题处理都在24小时左右，还请耐心等待
4. 感谢各位朋友的支持，如有其它需求，可以提交至iessus，多谢！

**Comment by solanana** [comment]
出现错误，错误信息:‘wx_id’←[0m   只会在群聊才会出现

**Comment by ngc660sec** [comment]
估计是获取不到@人的id导致的错误，可以贴上报错截图给我看看

> 出现错误，错误信息:‘wx_id’←[0m 只会在群聊才会出现

**Comment by solanana** [comment]
谢谢，已经解决，无法获取默认ID导致的，修改默认ID就行了 @ngc660sec

**Comment by docvirt** [comment]
作者大大 你好 on_message 为啥接收消息msgjson 中的"id3": "<msgsource>\n\t<signature>v1_JilxQb1J</signature>\n</msgsource>\n"
id3是一串签名的东东 @ngc660sec

**Comment by ngc660sec** [comment]
> 作者大大 你好 on_message 为啥接收消息msgjson 中的"id3": "\n\tv1_JilxQb1J\n\n" id3是一串签名的东东 @ngc660sec

你好 可能是微信版本不对，最近会更新机器人，我会研究的

**Comment by ngc660sec** [comment]
> > 作者大大 你好 on_message 为啥接收消息msgjson 中的"id3": "\n\tv1_JilxQb1J\n\n" id3是一串签名的东东 @ngc660sec
> 
> 你好 可能是微信版本不对，最近会更新机器人，我会研究的

你好，在近期的测试当中目前没发现这种问题哦

**Comment by Chinakentgao** [comment]
[ERROR]:AI对话接口错误，错误信息：'NoneType' object has no attribute 'strip' 这个是python版本问题？

**Comment by ngc660sec** [comment]
> ![1](https://user-images.githubusercontent.com/55339757/223910919-24feedf9-a0fe-453b-89ae-b8e9b2e8b695.png) [ERROR]:AI对话接口错误，错误信息：'NoneType' object has no attribute 'strip' 这个是python版本问题？python3.9.9跑的。检测到该问题属于敏感词，请重新提问， 敏感词为：【狗日】，若误拦请联系平台运营方，反馈过白 所有的参数全部都是去调用chatgpt那个接口导致什么都不能调用

你好，由于调用的第三方平台的ai对话接口，所以有限制，出现报错一般是AI对话接口故障

**Comment by daxian2022** [comment]
![c1ce1deba473b8e2668d7d9e0af20c3](https://github.com/ngc660sec/NGCBot/assets/97666690/a2d5917a-2341-4612-8e30-502db8780a4d)
你好，whois不返回消息，也不报错

**Comment by ngc660sec** [comment]
> ![c1ce1deba473b8e2668d7d9e0af20c3](https://private-user-images.githubusercontent.com/97666690/292706292-a2d5917a-2341-4612-8e30-502db8780a4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjM2MjUsIm5iZiI6MTcwNDI2MzMyNSwicGF0aCI6Ii85NzY2NjY5MC8yOTI3MDYyOTItYTJkNTkxN2EtMjM0MS00NjEyLThlMzAtNTAyZGI4NzgwYTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYmNiY2Y3ZWQ4YTEyNGNiNTNmZDk1YTg3NzYwNjA3OGU2MTdlNTQyYTJhYTZkMjdhNWNlMTJkZTY1ZDRlYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gyTYJXTFrCc5QdrL2B3xNDn8dRois5eMPcSy9WpGgns) 你好，whois不返回消息，也不报错

更新最新版本 进群说话兄弟们
