### ISSUE TITLE
想请问一下，为什么在群内输入开启推送后，虽然提示开启成功但还是不会自动推送，查看群聊也看不了

### ISSUE THREAD

**Issue by MyWorld319** [ngc660sec/NGCBot#30]

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    查看群聊没写 你可以看看数据库有没有这个群 按理来说是不会的
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月29日 09:23
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [ngc660sec/NGCBot] 想请问一下，为什么在群内输入开启推送后，虽然提示开启成功但还是不会自动推送，查看群聊也看不了 (Issue #30)
        
      
    
  
  


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by MyWorld319** [comment]
看了Point_db.db好像没有唉，是哪里有问题吗

**Comment by MyWorld319** [comment]
看了一下Point_db.db好像没有

**Comment by MyWorld319** [comment]
All_Db_File.db里是有记录的

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    删掉所有的db文件 重新启动一下
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月30日 10:41
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 想请问一下，为什么在群内输入开启推送后，虽然提示开启成功但还是不会自动推送，查看群聊也看不了 (Issue #30)
        
      
    
  
  
看了Point_db.db好像没有唉，是哪里有问题吗

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    按我说的试试。会自动初始化的 不可能没有
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月30日 14:56
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 想请问一下，为什么在群内输入开启推送后，虽然提示开启成功但还是不会自动推送，查看群聊也看不了 (Issue #30)
        
      
    
  
  
All_Db_File.db里是有记录的

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by MyWorld319** [comment]
全部删除重新初始化后就可以了，感谢大佬

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不客气，可以进群交流 我Github不怎么看
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月30日 17:01
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 想请问一下，为什么在群内输入开启推送后，虽然提示开启成功但还是不会自动推送，查看群聊也看不了 (Issue #30)
        
      
    
  
  
全部删除重新初始化后就可以了，感谢大佬

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
