### ISSUE TITLE
一点小小建议(这个项目应该火起来)

### ISSUE THREAD

**Issue by Kingziqiang** [ngc660sec/NGCBot#32]
[韩小韩API接口站](https://api.vvhan.com/)，都是免费接口，接口返回的数据更美观，更丰富，可玩性更高
但站长最近屏蔽了海外ip，出现问题的可以使用国内服务器
如果能在linux下部署，功能上在丰富一下，支持web设置。gpt接入fastgpt。那就完美了。

**Comment by ngc660sec** [comment]
这个接口站我看过 还可以
