### ISSUE TITLE
微信登录问题

### ISSUE THREAD

**Issue by Flyg2** [ngc660sec/NGCBot#34]
师傅麻烦问一下，为什么给的版本的微信登录显示登不上去，显示版本过低，有什么好的解决办法吗

**Comment by ngc660sec** [comment]
这个目前没有好的解决办法，只能换别的微信试试

**Comment by Flyg2** [comment]
我看文档上面说不能更新微信，如果换到高版本可以登录的微信会不会有影响

**Comment by Flyg2** [comment]
除了release中的微信版本还有其他版本可以用吗，刚才使用了官网下载的最新版本，注入报错dll错误

**Comment by ngc660sec** [comment]
最新的肯定不行的，你可以试试release版本中之前的版本

**Comment by alsjz** [comment]
现在微信旧版本是无法登录的

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    跟微信有关，我是可以登录的
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年05月3日 23:10
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 微信登录问题 (Issue #34)
        
      
    
  
  
现在微信旧版本是无法登录的

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by ngc660sec** [comment]
已解决，请进群交流
