### ISSUE TITLE
微信版本更新

### ISSUE THREAD

**Issue by Xudong-Mao** [ngc660sec/NGCBot#38]
微信版本过低不能登录提示，希望大大尽快跟进微信版本的更新

**Comment by ngc660sec** [comment]
群里有解决办法，后续版本正在更新

**Comment by finaluser** [comment]
如何加群呢？

**Comment by ngc660sec** [comment]
看readme即可

**Comment by chao128951523** [comment]
微信安装包我怎么找不到（小白）

**Comment by ngc660sec** [comment]
> 微信安装包我怎么找不到（小白）

在release里面

**Comment by Goldenbeef** [comment]
> 看readme即可

你好，添加机器人无反应，应该如何加群

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    待会我加你
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年06月14日 17:24
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 微信版本更新 (Issue #38)
        
      
    
  
  

看readme即可

你好，添加机器人无反应，应该如何加群
