### ISSUE TITLE
作者大大，调用舔狗日记API出现死循环，麻烦看一下

### ISSUE THREAD

**Issue by helloyangy** [ngc660sec/NGCBot#40]
![mmexport1716193293653](https://github.com/ngc660sec/NGCBot/assets/102957628/591c7a62-7b9e-47f6-b3bf-f7341fcd8199)

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好 配置一下config.yaml里面的key 不然就会一直调用 否则只能去修改代码 把重发功能去除
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年05月20日 16:22
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [ngc660sec/NGCBot] 作者大大，调用舔狗日记API出现死循环，麻烦看一下 (Issue #40)
        
      
    
  
  
mmexport1716193293653.jpg (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by helloyangy** [comment]
明白了，原来接口需要配置，感谢

**Comment by MaxSecurity** [comment]
老板解决了吗  我已经配置还是死循环

> 明白了，原来接口需要配置，感谢

**Comment by ngc660sec** [comment]
> 老板解决了吗 我已经配置还是死循环
> 
> > 明白了，原来接口需要配置，感谢

那就是key没申请接口权限
