### ISSUE TITLE
老板ai的接入好像有点BUG

### ISSUE THREAD

**Issue by MaxSecurity** [ngc660sec/NGCBot#41]
key什么的都填入了
![image](https://github.com/ngc660sec/NGCBot/assets/16812469/c1211b2d-901d-480a-b829-b427f9d227bb)

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    进群发我看看
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年05月21日 12:13
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [ngc660sec/NGCBot] 老板ai的接入好像有点BUG (Issue #41)
        
      
    
  
  
key什么的都填入了
image.png (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ngc660sec** [comment]
你确定所有的key都填了？怎么填的

**Comment by MaxSecurity** [comment]
> 你确定所有的key都填了？怎么填的

已加群

**Comment by YuLong-Liang** [comment]
借楼，请问下群在哪？

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好 添加机器人 回复进群 就可以进群
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            YuLong ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年09月5日 17:37
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 老板ai的接入好像有点BUG (Issue #41)
        
      
    
  
  
借楼，请问下群在哪？

**Comment by YuLong-Liang** [comment]
进群





------------------ 原始邮件 ------------------
发件人: 云云 ***@***.***&gt;
发送时间: 2024年9月5日 18:16
收件人: ngc660sec/NGCBot ***@***.***&gt;
抄送: YuLong Liang（梁玉龙） ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ngc660sec/NGCBot] 老板ai的接入好像有点BUG (Issue #41)





 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     你好 添加机器人 回复进群 就可以进群
     
         
             
         
     
     
     
     
 
     
 
     
 
   
     ---- 回复的原邮件 ----
   
   
     
       
         
          发件人 
         
         
             YuLong ***@***.***&gt;
             
         
       
       
         
          发送日期 
         
         
         2024年09月5日 17:37
         
       
       
         
          收件人 
         
         
          
           
             ***@***.***&gt;
             
           
         
       
       
         
          抄送人 
         
         
           
             ***@***.***&gt;
             ,
           
           
             ***@***.***&gt;
             
           
         
       
       
         
          主题 
         
         
               Re: [ngc660sec/NGCBot] 老板ai的接入好像有点BUG (Issue #41)
         
       
     
   
   
 借楼，请问下群在哪？
