### ISSUE TITLE
会不会导致微信被封？

### ISSUE THREAD

**Issue by kely2019** [ngc660sec/NGCBot#43]
这种自动化操作微信很容易被监控吧？

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    稳定一年没封 看你运气
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ngc660
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年05月22日 10:30
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [ngc660sec/NGCBot] 会不会导致微信被封？ (Issue #43)
        
      
    
  
  
这种自动化操作微信很容易被监控吧？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
