### ISSUE TITLE
使用了项目提供的微信，介绍的修复代码，执行结果一直是微信版本不对，无法修复，项目微信下载了很多次安装结果还是一样，求助！！

### ISSUE THREAD

**Issue by TerryZT** [ngc660sec/NGCBot#45]
1、所有安装完毕后，微信登录提示版本过低；
2、按照项目简介里面的方式，编辑执行，一直提示版本不对；（微信确定是项目提供的链接下载的，代码是复制的公众号的）
3、elif v != 0x63090217:  # 不是 3.9.2.23 修复也没用
            raise Exception("别修了,版本不对,修了也没啥用.")

**Comment by Goldenbeef** [comment]
请问代码在哪里找，现在群加不进去，公众号搜了一圈也没找到关于绕过低版本更新的相关文章。

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    在readme有的
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年06月14日 17:25
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 使用了项目提供的微信，介绍的修复代码，执行结果一直是微信版本不对，无法修复，项目微信下载了很多次安装结果还是一样，求助！！ (Issue #45)
        
      
    
  
  
请问代码在哪里找，现在群加不进去，公众号搜了一圈也没找到关于绕过低版本更新的相关文章。

**Comment by ngc660sec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    晚点拉你
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年06月14日 17:25
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ngc660sec/NGCBot] 使用了项目提供的微信，介绍的修复代码，执行结果一直是微信版本不对，无法修复，项目微信下载了很多次安装结果还是一样，求助！！ (Issue #45)
        
      
    
  
  
请问代码在哪里找，现在群加不进去，公众号搜了一圈也没找到关于绕过低版本更新的相关文章。
