### ISSUE TITLE
为什么配置了chatgpt的接口，但是系统老是去调用星火和讯飞呢？

### ISSUE THREAD

**Issue by 157243321** [ngc660sec/NGCBot#48]
![image](https://github.com/ngc660sec/NGCBot/assets/126582858/150a7171-9087-4a47-b46d-e6e0fec0b9a6)

**Comment by 157243321** [comment]
不好意思，是配置了chatgpt，第一句会去调用chatGPT，第2次再问就去调用星火和千帆（这2个都没有配置）

**Comment by ngc660sec** [comment]
好的，gpt错误就会自动调用另外两个

**Comment by 157243321** [comment]
> 好的，gpt错误自动调用另外两个

但是我的GPT是正常的哦，搞不懂，但是删除另外2个模型又无法启动

**Comment by ngc660sec** [comment]
不能删除的，gpt正常就行 先不管他 后面我再看看

**Comment by ngc660sec** [comment]
配置文件里面另外两个模型的配置随便写，最好别留空

**Comment by 157243321** [comment]
> 美国人在内部给两个模型随便配一个模型，最好是空

明白，谢谢领导
