### ISSUE TITLE
loadlibrary 调用失败

### ISSUE THREAD

**Issue by GideonZY** [ngc660sec/NGCBot#50]
微信版本3.9.2.23
最开始扫码登录微信提示版本号过低，使用工具后失败“别修了”
后尝试把工具的 if 语句注释掉了，成功打开
添加完管理员后再启动就报错调用失败
有时可以启动有时不行
<img width="1239" alt="image" src="https://github.com/ngc660sec/NGCBot/assets/61855669/866ca1b5-dd5c-4f4d-82f9-73b841e58536">
<img width="459" alt="image" src="https://github.com/ngc660sec/NGCBot/assets/61855669/1c02c4e1-b4fd-471b-b83d-ceb85e3756a7">

**Comment by ngc660sec** [comment]
你好 任务管理器关闭微信重启打开 每次打开微信都要运行修复脚本

**Comment by GideonZY** [comment]
尝试了，有几率打开，但是大概率还不行，甚至重启了也不行。。。。

**Comment by ngc660sec** [comment]
也可能是微信自动更新 导致 建议重新安装微信 运行脚本启动

**Comment by GideonZY** [comment]
重装微信已解决
