### ISSUE TITLE
使用你上传的微信3.9.2.23.exe，然后执行main文件提示不支持当前版本

### ISSUE THREAD

**Issue by liuqinchong** [ngc660sec/NGCBot#52]
![image](https://github.com/ngc660sec/NGCBot/assets/67302310/1f2d99c6-bb86-4a33-9b41-028f8e990dbd)
<img width="107" alt="微信截图_20240704142810" src="https://github.com/ngc660sec/NGCBot/assets/67302310/5433a1e3-4421-4f75-9371-d4561d92bf9a">

**Comment by ngc660sec** [comment]
看看是不是自动更新了

**Comment by liuqinchong** [comment]
> 看看是不是自动更新了

没有自动更新，我验证过了，使用2.0版本的代码，无法使用3.9.2.23.exe和3.2.1.121的微信。使用1.5的代码可以使用3.2.1.121的微信

**Comment by ngc660sec** [comment]
卸载所有的python库重新install
