### ISSUE TITLE
ai的key在哪里配置呢

### ISSUE THREAD

**Issue by dzw814029264** [ngc660sec/NGCBot#6]

**Comment by dzw814029264** [comment]
AI对话接口错误，错误信息：Expecting value: line 1 column 1 (char 0)

**Comment by MyWorld319** [comment]
[ERROR]:AI对话接口错误，错误信息：'NoneType' object has no attribute 'strip'

**Comment by MyWorld319** [comment]
我回复help的时候，他会返回检测到该问题属于敏感词，请重新提问，
                敏感词为：【help】，若误拦请联系平台运营方，反馈过白

**Comment by ngc660sec** [comment]
> AI对话接口错误，错误信息：Expecting value: line 1 column 1 (char 0)

AI调用的第三方接口，没有设置KEY的选项
Expecting value: line 1 column 1 (char 0)
此错误需要详细截图

**Comment by ngc660sec** [comment]
> [ERROR]:AI对话接口错误，错误信息：'NoneType' object has no attribute 'strip'

你好，此问题一般对应与AI API接口没有返回出现的报错
若误拦请联系平台运营方，反馈过白
因为是调用的第三方的API，所以限制比较严格，在源码中也没有相应的配置去进行修改，如果可以的话，最好是自己修改AI API方法
