### ISSUE TITLE
【已解决】本地搭建了fastgpt，请问如何接入？

### ISSUE THREAD

**Issue by JIGEEE** [ngc660sec/NGCBot#61]
本地搭建了fastgpt测试可用，有api地址和apikey，请问在配置文件中如何接入。网上相关资料查询到直接填入openai相关设置里，测试无效。

直接将fastgpt应用API key填入openai接口处（如何获得应用API key看fastgpt文档）

**Comment by xw19930** [comment]
同问，求大佬解答

**Comment by rongwei-lab** [comment]
你好，我问下，这个后来你是怎么解决的 @JIGEEE

**Comment by ngc660sec** [comment]
> 本地搭建了fastgpt测试可用，有api地址和apikey，请问在配置文件中如何接入。网上相关资料查询到直接填入openai相关设置里，测试无效。
> 
> 直接将fastgpt应用API key填入openai接口处（如何获得应用API key看fastgpt文档）

需要对接fastapi 要加代码

**Comment by rongwei-lab** [comment]
好的，谢谢
