### ISSUE TITLE
安装依赖后，运行main.py后报错

### ISSUE THREAD

**Issue by a877429929** [ngc660sec/NGCBot#62]
![image](https://github.com/user-attachments/assets/b6f3774d-cd0f-4d1a-85f3-8df3e2bec0a1)

**Comment by ngc660sec** [comment]
你好 检查微信版本和 wcf 版本是否对应 另外 Windows 系统最好采用 Win10 WInServer2019 不能使用过低版本 Python 版本选择 3.8.10

**Comment by a877429929** [comment]
> 你好 检查微信版本和 wcf 版本是否对应 另外 Windows 系统最好采用 Win10 WInServer2019 不能使用过低版本 Python 版本选择 3.8.10

你好，确认过了，wcferry==39.2.4.0，用的微信版本3.9.10.27，Python版本是3.10.11，但是windos用的是ltsc版本，不知道是不是这个问题呢

**Comment by ngc660sec** [comment]
windows是什么版本呢 win2019 还是

**Comment by a877429929** [comment]
> windows是什么版本呢 win2019 还是

你好，是win10 专业版 LTSC
![image](https://github.com/user-attachments/assets/03194ce6-91ef-4d51-8275-df828a566e7a)

**Comment by ngc660sec** [comment]
> > windows是什么版本呢 win2019 还是
> 
> 你好，是win10 专业版 LTSC ![image](https://private-user-images.githubusercontent.com/73450291/360403298-03194ce6-91ef-4d51-8275-df828a566e7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjQ5OTAsIm5iZiI6MTcyNDMyNDY5MCwicGF0aCI6Ii83MzQ1MDI5MS8zNjA0MDMyOTgtMDMxOTRjZTYtOTFlZi00ZDUxLTgyNzUtZGY4MjhhNTY2ZTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzZmZGIzNmYyOTlmYWQ2M2Q0ZjExZjFhMDFjM2Q4OTc1NWYyNjZhMGU1Zjc3YzI3M2I1MTZjZjdlM2ZkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23vUEsF30kNB1xWMRpemCuY61CcmeM_PYyecjD1iDOM)

麻烦添加一下微信机器人 回复 【开发者】进群，联系群主 远程帮你看看

**Comment by a877429929** [comment]
好的，谢谢！
