### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by baddogly** [ngc660sec/NGCBot#67]
███▄▄▄▄      ▄██████▄   ▄████████ ▀█████████▄   ▄██████▄      ███
███▀▀▀██▄   ███    ███ ███    ███   ███    ███ ███    ███ ▀█████████▄
███   ███   ███    █▀  ███    █▀    ███    ███ ███    ███    ▀███▀▀██
███   ███  ▄███        ███         ▄███▄▄▄██▀  ███    ███     ███   ▀
███   ███ ▀▀███ ████▄  ███        ▀▀███▀▀▀██▄  ███    ███     ███
███   ███   ███    ███ ███    █▄    ███    ██▄ ███    ███     ███
███   ███   ███    ███ ███    ███   ███    ███ ███    ███     ███
 ▀█   █▀    ████████▀  ████████▀  ▄█████████▀   ▀██████▀     ▄████▀
     Version: V2.1
     Author: 久安信息有限公司旗下-NGC660安全实验室(eXM/云山)
初始化失败！
PS F:\0wish\0网页\NGCBot-master>

**Comment by ngc660sec** [comment]
任务管理器关闭微信重新打开

**Comment by 3CB3EC** [comment]
查下python包wcferry版本，我根据主页上引导装了以后，版本并非主页上说的那个版本，表现就是和你一样，根据wcferry版本重新装对应的微信版本就行
