### ISSUE TITLE
登录后程序执行失败

### ISSUE THREAD

**Issue by hackpwnpwn** [ngc660sec/NGCBot#7]
![image](https://user-images.githubusercontent.com/57691997/223672408-c7e5a42c-0a21-4701-9b32-f24ca1e9b915.png)
在主界面注入成功执行main.py后，点击登录一直卡在heart beat

**Comment by ngc660sec** [comment]
> ![image](https://user-images.githubusercontent.com/57691997/223672408-c7e5a42c-0a21-4701-9b32-f24ca1e9b915.png) 在主界面注入成功执行main.py后，点击登录一直卡在heart beat

你好 一般是昵称解析问题，请看下其它功能是否正常
