### ISSUE TITLE
judgeEqualListWord异常

### ISSUE THREAD

**Issue by wqqqqqq200** [ngc660sec/NGCBot#72]
1.复现：如果关键词列表为空，会报错TypeError: 'NoneType' object is not iterable
2.完善：在for循环前增加为空判断，如果为None 那么直接返回False
def judgeEqualListWord(recvWord, systemListWord):
    """
    判断接收消息在触发关键字列表中则返回True
    接收消息 in ['触发关键字列表']
    :param recvWord: 接收消息
    :param systemListWord: 触发关键字列表
    :return:
    """
    if systemListWord is None:
        return False  
    for listWord in systemListWord:
        if listWord.strip() == recvWord.strip():
            return True
    return False

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the judgeEqualListWord function to include a check for None before iterating through the systemListWord list. This prevents the TypeError when the list is empty.

You can review changes in this commit: https://github.com/kkpo4553/ngc660sec-NGCBot-72/commit/e28630efbd5730cbe4b70e00737fdac64d9d2bbb.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
