### ISSUE TITLE
您好 会考虑增加获取新增好友确认收款邀请入群等功能么

### ISSUE THREAD

**Issue by shaolintong** [ngc660sec/NGCBot#8]
您好 会考虑增加获取新增好友确认收款邀请入群等功能么

**Comment by ngc660sec** [comment]
> 您好 会考虑增加获取新增好友确认收款邀请入群等功能么

你好，此机器人采用微信hook机制，其hook代码为@cixingguangming55555大佬撰写，你得问这个大佬

**Comment by shaolintong** [comment]
好的 谢谢
